### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by cabo40** [ibmdb/rust-ibm_db#1]
Hi, I can't compile the code with `cargo build` on a `x86_64-unknown-linux-gnu` platform. My rustc version is 1.49.0
the error I get is
`error[E0512]: cannot transmute between types of different sizes, or dependently-sized types`

**Comment by mijailo** [comment]
Hi!
I have the very same problem on building this repo: 

```
[rust-ibm_db] $ cargo build                                             
   Compiling ibm_db v0.1.2 (/home/misha/Documentos/Laburo SAT/Desarrollos e investigación/SCCCyG/scccyg-rs/rust-ibm_db)
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
     --> src/lib.rs:27762:18
      |
27762 |         unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 8u8) as u32) }
      |                  ^^^^^^^^^^^^^^^^^^^^^
      |
      = note: source type: `u32` (32 bits)
      = note: target type: `u64` (64 bits)
      (...)
```
 which appears around 530 times. Is there any specific way to solve this by means of the `examples/setup.rs`?
 Thanks in advance!

**Comment by AWADHAMBIKA** [comment]
Hi @mijailo & @cabo40,
This is still WIP and lib.rs is windows sub-version of the final version. This the reason you are getting error on LINUX OS.
Currently only setup.rs(which is a tool to download the CLI driver) is LINUX compatible.
For the same to be used you need to run the following command: 
sudo cargo run --package Rust_C_Sample --example setup

Also, I have compiled the lib.rs for LINUX(lib_unix.rs) and have uploaded the same under src folder.

I have updated the install instructions in readme.md. Kindly refer to the same for your platform.

**Comment by mijailo** [comment]
Thank you for your help! The compilation almost succeeded:
   ```bash
...
   Compiling reqwest v0.10.10
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed"
...
   ```
I have been told that the last requirement, is the DB2 `*.so` files. Do you have any suggestion on how to include in the source code an automatic downloading ?
Best regards !

**Comment by AWADHAMBIKA** [comment]
Hi @mijailo,
As you might already know, DB2 *.so is nothing but CLI driver.
The step to download the same is mentioned in README.md file i.e.
`cargo run --package Rust_C_Sample --example setup`
Then you have to make sure that IBM_DB_HOME and LD_LIBRARY_PATH is set to downloaded location.

NOTE: Currently automatic downloading is not happening as I am not aware of if RUST supports the same and is not a good coding practice. It only suggests to package the required binary but we have different binary(i.e. CLI Driver executable) for different platforms so currently, we haven't packaged.

We are working on it and hope auto-download will be possible in future.
