### ISSUE TITLE
Panic when sql statements encounter null at ibm_db::raii::Raii<odbc_sys::Stmt>>::get_partial_data

### ISSUE THREAD

**Issue by mdgozza** [ibmdb/rust-ibm_db#4]
When making a valid query ( which works with jdbc just fine ) I get a panic:

`'no more data but indicatior outside of data buffer'`

How can I help reproduce this issue for further debugging? 

Here is what the snippiet of rust that executes the query looks like:

```rust
match stmt.exec_direct(&query.query) {
        Ok(data) => match data {
            Data(mut data) => {
                let cols = data.num_result_cols().unwrap();

                for i in 1..(cols + 1) {
                    col_names.push(data.describe_col(i as u16).unwrap());
                }

                while let Some(mut cursor) = data.fetch().unwrap() {
                    let mut record: HashMap<&str, std::string::String> = HashMap::new();
                    for i in 1..(cols + 1) {
                        let col_name = &col_names[i as usize - 1];
                        match cursor.get_data::<&str>(i as u16).unwrap() {
                            Some(val) => {
                                record.insert(&col_name.name, val.to_owned());
                                
                            }
                            None => println!("NULL"),
                        }
                    }
                    result.push(record);
                }
            }
            NoData(_) => println!("got no data"),
        },
        Err(e) => println!("got an err: {}", e),
    }
```

I will update this with more information as I learn more for now I believe I've isolated the part of the query that causes the panic down to **EDIT**: Any query that produces null values

I was able to trace the panic back to here:
https://github.com/ibmdb/rust-ibm_db/blob/main/src/statement/output.rs#L68-L72

~~still investigating why case statements cause this problem...~~ Correction: any sql statement that produces null values will cause a panic

**Comment by mdgozza** [comment]
Updating the issue with more information -  I have been able to destill the cause to when a query encounters a null return value: 

See this example sql

```sql
select CASE
    WHEN (
      FINAPP.ID IS NOT NULL
      AND FINAPP.ID > 0
    ) THEN FINAPP.ID
  END as "financeAppId",
  CASE
    WHEN (
      FINSTORE.STDIV IS NOT NULL
      AND FINRESP.APPLICATIONID IS NOT NULL
    ) THEN 1
    ELSE 0
  END as "preApproved",
  CASE
    WHEN (
      FINSTORE.STDIV IS NOT NULL
      AND FINRESP.APPLICATIONID IS NOT NULL
    ) THEN FINRESP.CREDITLIMIT
    ELSE 0.00
  END as "creditLimit",
  CASE
    WHEN (
      FINSTORE.STDIV IS NOT NULL
      AND FINRESP.APPLICATIONID IS NOT NULL
    ) THEN TRIM(FINRESP.FINANCEVENDORCODE)
  END as "vendorCode"
from QS36F.FINAPP as FINAPP
  LEFT JOIN QS36F.FINRESP AS FINRESP ON FINRESP.APPLICATIONID = FINAPP.ID
  AND (
    FINRESP.APPROVALCODE = '05'
    OR FINRESP.APPROVALCODE = '10'
  )
  AND FINRESP.APPLICATIONTYPE = 'QS'
  AND DATE (FINRESP.OFFEREXPIRATIONDT) >= DATE (current timestamp)
  LEFT JOIN QS36F.STORE as FINSTORE ON FINSTORE.STSTON = FINRESP.PHYSICALSTORE
limit 5
```
The JDBC driver produces this output

```json

  {
    financeAppId: 1208882,
    preApproved: 0,
    creditLimit: '0',
    vendorCode: null
  },
  {
    financeAppId: 1208883,
    preApproved: 0,
    creditLimit: '0',
    vendorCode: null
  },
  {
    financeAppId: 1208884,
    preApproved: 0,
    creditLimit: '0',
    vendorCode: null
  },
  {
    financeAppId: 1208885,
    preApproved: 0,
    creditLimit: '0',
    vendorCode: null
  },
  {
    financeAppId: 1208886,
    preApproved: 0,
    creditLimit: '0',
    vendorCode: null
  }
]
```

but the rust example panics.

When removing the last case statement - the query in rust succeeds.

**Comment by mdgozza** [comment]
Checking DataGrip with this example SQL and comparing its result to the `output.rs` file, I can only assume that the indicator returned is not matching `ffi::SQL_NULL_DATA` - put perhaps another match that might exist and also means null?
![image](https://user-images.githubusercontent.com/9098106/116275986-1536c580-a752-11eb-9d98-74d5fd2fd59b.png)

https://github.com/ibmdb/rust-ibm_db/blob/main/src/statement/output.rs#L66-L72

**Comment by mdgozza** [comment]
I can confirm that locally, PR#6 fixes this issue for me and now `null` SQL values match the `None` Enum.

**Comment by AWADHAMBIKA** [comment]
Thanks @mdgozza I was able to replicate the issue by using "left outer join" as you pointed and the issue was resolved with the code fix i.e.  `if start_pos + indicator as usize >= buffer.len() {
                        Return::Success(None)
                    }else{` instead of `assert!(start_pos + indicator as usize <= buffer.len(), "no more data but indicatior outside of data buffer");`

I would run few more tests before I merge the changes.
Looks good and thanks again for your help :)

**Comment by AWADHAMBIKA** [comment]
Have checked in the relevant code and have closed the pull request.
Thanks again for pointing the issue and resolving it. Cheers!
